[book]
authors = ["Eric Hamiter"]
language = "en"
multilingual = false
src = "src"
title = "IPython for Web Devs"

[output.html]
theme = "src/theme"
git-repository-url = "https://github.com/ehamiter/ipython-book"
curly-quotes = true

[output.html.fold]
enable = false
level = 0
